apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: sensor_data
    user: root
    secureJsonData:
      password: root
    isDefault: true
